### PR TITLE
Add Java Docs to the Readme

### PR DESCRIPTION
**Pull request by tomlister**
Just makes the full docs a little more accessible.

### CODE REVIEW

**Comment by tomlister** [comment]
Any update on this?

**Comment by zml2008** [comment]
no

**Comment by tomlister** [comment]
> no

Justify to clarify. No updates on this yet or just no to the whole PR?

Cheers.

**Comment by kezz** [comment]
I don't want the badge to say the version number as that's just another thing we have to remember changing. Perhaps just change it to `javadocs | all`?

**Comment by tomlister** [comment]
Cheers Kezz, I'll change this now. I understand that it could be quite
frustrating having to remember to change the version number, especially
when you have to change it in so many other places! 😂

**Review by kezz — APPROVED** [review]

**Comment by zml2008** [comment]
Javadoc, not JavaDocs please

**Pull request merged**
