### PR TITLE
Expose WrappingComponentLoggerImpl through ComponentLogger

### PR DESCRIPTION
**Pull request by JRoy**
there's this perfectly good logger impl here and im just tryin to use it

### CODE REVIEW

**Comment by zml2008** [comment]
what are you trying to do? this is really for use by platforms, not by end users?

**Comment by JRoy** [comment]
> what are you trying to do? this is really for use by platforms, not by end users?

Want to use this for Paper (where we don't need to change anything in WrappingComponentLoggerImpl other than the underlying serializer), kash told me to make a static method for it

**Comment by zml2008** [comment]
The point of the service provider is so that *any* logger created uses the correct serializer, not just some magical 'blessed' loggers you choose. Why does the service provider not work?

**Comment by JRoy** [comment]
discussed internally that I'm a dumbass

**Pull request closed without merging**
