### PR TITLE
Redundant Collection.addAll() call

### PR DESCRIPTION
**Pull request by oguzhancevik**
Redundant Collection.addAll() call 
This commit helps to open source community for Hacktoberfest.

### CODE REVIEW

**Comment by kashike** [comment]
Sorry, we will not be accepting this pull request at this time.

**Comment by oguzhancevik** [comment]
@kashike why?

**Comment by kashike** [comment]
I have refactored this code locally - the code you are changing is gone.

**Comment by oguzhancevik** [comment]
At least you can add a hacktoberfest-accepted label.

**Comment by kashike** [comment]
This pull request was not accepted, so it makes no sense to do so.

**Pull request closed without merging**
