### PR TITLE
text-minimessage: Allow tags to be closed in one tag

### LINKED ISSUE #523: Add a way to prevent templates impacting remaining content
Something like `<my_template/>` which would resolve the template whilst preventing any tags inserted from bleeding into remaining strings.

Essentially shorthand for `<span><my_template></span>`, considering KyoriPowered/adventure-text-minimessage#178.

### LINKED ISSUE #704: Support self-closing tags in the parser
To be able to distinguish between components with no children and components who have all following content as a child, we should be able to have `<tag/>` be equivalent to `<tag></tag>` in the parser and serializer.

This would fully close #523.

### PR DESCRIPTION
**Pull request by zml2008**
This simplifies the language for tags with no children.

### CODE REVIEW

**Review by kezz — APPROVED** [review]

**Comment by rymiel** [comment]
This doesn't implement #523, just adds the tokenization capabilities, right?
Is emitting lang and key tags as self-closing something we want? Maybe makes it imply those have children taking #523 into context

**Comment by rymiel** [comment]
disregard the first part of that comment, `testIgnorableSelfClosable` addresses that

**Comment by zml2008** [comment]
To support vanilla components properly, I made all of the standard tags able to have children, since all component types can have children normally. The forced-no children attribute on Inserting tags is really just for custom things -- so there should probably be an attribute on the serializer to generate those sort of tags without the closing slash.

The only situation where that's relevant in MM itself is probably the newline tag though, since that's theoretically serializable (though, due to compaction it often won't end up as a separate component).

**Review by rymiel — APPROVED** [review]
Today i learned those components can have children in vanilla, sounds messy

**Pull request merged**
