### PR TITLE
feat(minimessage): Pride tag

### PR DESCRIPTION
**Pull request by kezz**
It's surprising how often I have to hand type pride gradients. Anyway, happy pride gamers 🏳️‍🌈

image

### CODE REVIEW

**Review by zml2008 — APPROVED** [review]

**Comment by mudkipdev** [comment]
Do you think it's also possible to add a pride tag which uses the raw colors instead of smooth gradients

**Comment by zml2008** [comment]
I think that'd be a great idea for pride next year :3 (as in, that sounds possible but also would take more time than simply repurposing the gradient tag)

**Comment by kezz** [comment]
Wouldn't be a hard tag to make, would be nice to make it generic then repurpose it for pride like this tag. Any name ideas for the tag?

**Review by 5RoD — COMMENTED** [review]
what the fuck is this

**Comment by carlosleondev** [comment]
where is the flag of heterosexuals?

**Comment by iAtog** [comment]
> where is the flag of heterosexuals?

There is no such thing as heterosexuals

**Pull request merged**
