### PR TITLE
revise: MiniMessageTranslator #972

### PR DESCRIPTION
**Pull request by KKW557**
This PR is based on the original PR [#972 ](https://github.com/KyoriPowered/adventure/pull/972). The original PR was not merged due to several review comments, and the original author is no longer making updates. To continue the development and integration of this feature, I have revised and improved the initial submission.

### CODE REVIEW

**Review by powercasgamer — CHANGES_REQUESTED** [review]
I don't really see a point in this? Besides the fact that the other PR is still marked as a draft, Kezz should be marked as the main author and you as a co author at least.

**Comment by KKW557** [comment]
> I don't really see a point in this? Besides the fact that the other PR is still marked as a draft, Kezz should be marked as the main author and you as a co author at least.

His activities have been gone for three months, and I'm not the author or co author, I think the feature is good but it hasn't been changed in a long time

**Comment by masmc05** [comment]
There should be a reason why he didn't finish or why he didn't mark the pr as ready, and the author is active, just not on that pr.

Be patient

**Comment by kezz** [comment]
The original PR is waiting on virtual components for named arguments (i.e. `<name>` instead of `<arg:1>`).

**Pull request closed without merging**
