### PR TITLE
Implement TransitionTag

### LINKED ISSUE #673: Feature request: Complete small phase to big phase text gradient transition
Hi all,

I'd love a new feature to be added, which allows me to use MiniMessage to implement a small phase to big phase full gradient transition of a string. For example, I'd like a small sentence to start off white, and slowly turn into yellow. I was thinking a syntax like this could suffice;

```<transition:#000000:#FFFFFF:60>```

where `#000000` is the starting color, `#FFFFFF` is the final color, and `60` is the percentage of transition.

Please let me know what you think.

Thank you

### PR DESCRIPTION
**Pull request by MiniDigger**
https://streamable.com/ysh2r5

https://streamable.com/o3g0qn

```java
      sender.sendMessage("transition:white:black:red");
      for (float phase = 0; phase <= 1; phase += 1 / 16f) {
        sender.sendMessage(MiniMessage.miniMessage().deserialize("<transition:white:black:red:" + phase + ">Hello World " + phase));
        Thread.sleep(100);
      }
      sender.sendMessage("transition:white:black:red:blue");
      for (float phase = 0; phase <= 1; phase += 1 / 16f) {
        sender.sendMessage(MiniMessage.miniMessage().deserialize("<transition:white:black:red:blue:" + phase + ">Hello World " + phase));
        Thread.sleep(100);
      }
      sender.sendMessage("- 1 transition:white:black:red");
      for (float phase = -1; phase <= 1; phase += 1 / 16f) {
        sender.sendMessage(MiniMessage.miniMessage().deserialize("<transition:white:black:red:" + phase + ">Hello World " + phase));
        Thread.sleep(100);
      }
      sender.sendMessage("- 1transition:white:black:red:blue");
      for (float phase = -1; phase <= 1; phase += 1 / 16f) {
        sender.sendMessage(MiniMessage.miniMessage().deserialize("<transition:white:black:red:blue:" + phase + ">Hello World " + phase));
        Thread.sleep(100);
      }



      for (int i = 0; i < 1000; i++) {
        final double angle = (2.0 * Math.PI * i) / 100;
        final double sin = Math.sin(angle);
        sender.sendMessage(MiniMessage.miniMessage().deserialize("<transition:white:black:red:blue:" + sin + ">Hello World " + sin));
        Thread.sleep(100);
      }

```

### CODE REVIEW

**Comment by zml2008** [comment]
blocked by #672

**Review by kezz — APPROVED** [review]
Needs a matching docs PR/issue but LGTM!

**Comment by kezz** [comment]
Would be nice in the future to abstract more of this logic out somehow. Still a lot repeated between here and the new abstract class for gradients/rainbows.

**Comment by MiniDigger** [comment]
docs pr https://github.com/KyoriPowered/adventure-docs/pull/67

**Review by zml2008 — APPROVED** [review]

**Pull request merged**
